Countries.Web/Models/ErrorViewModel.cs
using System;

namespace Countries.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Countries.Web/Controllers/CountryController.cs
using Countries.Database.Repositories;
using Domain;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Countries.Web.Controllers
{
    public class CountryController : Controller
    {
        private readonly ICountryRepository _countryRepository;
        public CountryController(ICountryRepository countryRepository)
        {
            _countryRepository = countryRepository;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return View(_countryRepository.Get().ToList());
        }

        public ActionResult Search()
        {
            return View();
        }
        public ActionResult Details(string country)
        {
            var v = new CountryLoader().LoadInfo(country).Result;
            return View(v);
        }

        public ActionResult Save(CountryDisplayModel country)
        {
            _countryRepository.Create(country);
            return RedirectToAction("List");
        }

        public ActionResult Delete(long id)
        {
            _countryRepository.Delete(id);
            return RedirectToAction("List");
        }
    }
}

Countries.Web/Views/Country/Details.cshtml
@model Domain.Models.CountryDisplayModel

@{
    ViewData["Title"] = "Search";
}

<h1>Search</h1>

@if (Model == null)
{
    <h2>Not found</h2>
    <a asp-action="Search">Back to search</a>
}
else
{


    @using (Html.BeginForm("Save", "Country"))
    {

        <div>
            <h4>@Model.Name</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Alpha3Code)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Alpha3Code)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Area)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Area)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Population)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Population)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Capital)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Capital)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Region)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Region)
                </dd>
            </dl>
        </div>


        @Html.HiddenFor(model => model.Name)
        @Html.HiddenFor(model => model.Capital)
        @Html.HiddenFor(model => model.Alpha3Code)
        @Html.HiddenFor(model => model.Area)
        @Html.HiddenFor(model => model.Population)
        @Html.HiddenFor(model => model.Region)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save to database" class="btn btn-primary" />
            </div>
        </div>


    }
}
<div>
    <a asp-action="List">Back to List</a>
</div>

Countries.Web/Views/Country/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <!--<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">-->@*building Web apps with ASP.NET Core*@<!--</a>.</p>-->
    <p>By this app you can search information about counties and save it to database.</p>
    <div class="form-group">
        <div class="col-md-offset-2">
            <a href="/Country/List/" class="btn btn-primary">List of saved countries</a>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2">
            <a href="/Country/Search" class="btn btn-primary">Search country</a>
        </div>
    </div>
</div>

Countries.Web/Views/Country/List.cshtml
@model IEnumerable<Domain.Models.Country>

@{
    ViewData["Title"] = "List";
}

<h1>Saved countries</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Area)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Population)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capital)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Population)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capital.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region.Name)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Countries.Web/Views/Country/Search.cshtml
<h1>Search country</h1>

@using(Html.BeginForm("Details", "Country"))
{
<div class="form-inline">

    <input type="text" name="country" class="form-control" />    
    <input type="submit" value="Search" class="btn btn-primary" />
</div>
}

Countries.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Countries</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Country" asp-action="Index">Countries</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="List">Saved countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Search">Search country</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Countries.Web 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>